travis:
  secure:
    BINSTAR_TOKEN: BCdvu72yDfWwAS4gFW5C6qYfmYJGw1dF6hM7bYjg9yzU5f2e0Wu0PUOuAD5EZg7+IuuJH/UXBGpW9tqcfJEK2SxlxtdvNix7hN6TJXV5GnIqW202x+EPcYs6y5jcZ8se5oWx/SPyf6+4XMVCeCFWP4Vuw/hkqsujawCjJc3zSLd2lBlF+a6plQmtK5WEyDWOx2fcMX5CVOtUJBFobi1zMXYro/vmrm1Fl98lKaup+gmtjt7ukjPieZ66VcFK/XN8OxJoTh38MXybvgqt+R1fov/X0cBczGMS8edZ1bB3tNPRFHGOUFtC/2CHZwG0lJI9DCzE0A9jTbvUNw2Z8VfkOcSqlMyfvrbGYOA/W1yBtH15xPbb8EWzmQGo08F+3cKcG3x0kkyJIDk2hJltTeVzc3km9Tg5PsZBIJQXdrDhqZyIq3wp0BintHUB3MoEjVBd6Ive1EWZxNV5xL1ezFPciKo0BIlRID+/mhG+1Lo1U3Fcej7z+51C+jojLcOnCFmbG7iUvX2LZM8DcC7uBAnX4WkWrpQ4ODrDlJQUqTe+jmEbUm86mZKk3xjuB+zmOqs1HNK2PrB/iTKIU+HUIv7nLbl2lx+MNcdtBqA/65euNKPYxslmAzlyhXXbZgFeoRGG1XInSVpDzlLmLEVFbfWgdU2CeICJ4wPQeuqa2wkzOO8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
